-   id: autopep8
    name: autopep8
    description: ''
    entry: autopep8
    language: python
    'types': [python]
    args: ["-i"]
    require_serial: false
    additional_dependencies: []
    minimum_pre_commit_version: '0'
